language: generic
sudo: required
services:
  - docker

before_install:
   docker pull ubuntu:bionic;
   docker run --name ubuntu -it -d ubuntu:bionic /bin/bash;

script:
  - docker exec ubuntu apt-get -qq update
  - docker exec ubuntu apt-get -y dist-upgrade
  - docker exec ubuntu apt-get -y install cmake lsb-release wget libminizip-dev libsdl2-dev libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev pkg-config zlib1g-dev binutils-dev libspeexdsp-dev libsamplerate0-dev awscli qt5-default build-essential nasm git zip clang
  - docker exec ubuntu git clone --recursive https://github.com/m64p/mupen64plus-GLideN64.git
  - docker exec ubuntu /bin/bash -c "export AWS_ACCESS_KEY_ID=$ACCESS_KEY; export AWS_SECRET_ACCESS_KEY=$SECRET_KEY; cd mupen64plus-GLideN64; if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then ./build.sh aws; fi"
